try{
    throw "";
}
catch(e){
    console.log("Відбулася помилка");
}
finally{
    console.log("Помилки оброблені");
}